### ISSUE TITLE
cannot install CF

### ISSUE THREAD

**Issue by lichingyun** [jooooscha/Olauncher#10]
![Screenshot_20220423-063300_F-Droid](https://user-images.githubusercontent.com/79099214/164877768-195447f3-0210-4872-aed5-fc8ab87954c5.png)

I can't install Olauncher CF on my Redmi Note 5 Whyred with android 12.1 (Arrow Os)
I don't understand the meaning of the error message, I am not a programmer 🙏
The first line of the message meaning: Error during the install of...

**Comment by Ilithy** [comment]
Sure enough, I also get an error when trying to install OLauncher CF. "invalid packages"

![Screenshot_20220423-074816](https://user-images.githubusercontent.com/36798218/164880301-73aa4848-a3f5-49b0-b1c9-d493f0ee10a7.png)

**Comment by jooooscha** [comment]
I cannot confirm. Just installed in on my Tablet (Android 9) and also installed it on my phone (Android 11)

Maybe try to update your repos? Otherwise this seems to be and F-droid bug?

Did you confirm the apk file is not corrupted?

**Comment by Ilithy** [comment]
@jooooscha It must be during the compilation done by Fdroid because I tried to directly download the apk from Fdroid, I get a error:

_an error occurred while parsing the package_

is it possible for you to provide a test apk directly compiled by you to verify the installation on our devices?

**Comment by jooooscha** [comment]
Sure, I have uploaded the last apk output from Android Studio to my nextcloud: https://next.serwm.com/s/n7wo4nMn6w3qwm5

**Comment by ferlanero** [comment]
I can confirm that OLauncher Clutter Free F-Droid release is installing correctly over Android 10. Moreover, I have to admit that the result is spectacular due to its fluidity and good organization. Congrats to its developer!!

**Comment by lichingyun** [comment]
> Sure, I have uploaded the last apk output from Android Studio to my nextcloud: https://next.serwm.com/s/n7wo4nMn6w3qwm5

I download this file but I have an error message:

an error occurred while parsing the package

I am using Android 12.1 on a Xiaomi Redmi Note 5

**Comment by drmrl** [comment]
From what I see, a user and the dev have verified on android 9, 10, 11  but us v12 users are stuck. Sucks cuz this would have have solved 1 of the 2 things the main has that I wanted handled. So wanting app renaming, and then rip out ALL internet access. That would be my ideal.

**Comment by jooooscha** [comment]
Ok, maybe I have messed something up in the gradle configs, I will try what I can do. PRs welcome.

The removal of the internet access permisson is also on my whislist. I think I should open a whishlist issue to keep track of such things

**Comment by jooooscha** [comment]
I have fixed some things and it works in my android 12 emulator.

Theoretically, GitHub should build the app now with every release but it seems not to work as of yet (see #9)

Therefore, I have uploaded another apk to my nextcloud: https://next.serwm.com/s/n7wo4nMn6w3qwm5

Please test and provide feedback. Thanks :)

**Comment by lichingyun** [comment]
@jooooscha I try to install the new .apk but I have the same error message

**Comment by drmrl** [comment]
Confirmed app-debug2.apk error: "you can't install the app on your device"

**Comment by jooooscha** [comment]
I am really sorry that it does not work for you. Sadly, I have currently little time to work on this, but I am going to look into it as soon as possible.

**Comment by jooooscha** [comment]
Ok, I have uploaded another apk. I might have mixed up the apk files, so if this one works, the next release in f-droid will as well (should be ready any time now)

**Comment by lichingyun** [comment]
@jooooscha I have installed the new apk, it works 😍👍
Is beautiful to read the menu in italian using my translation 😄
Now I need to configure and use it... I have only one suggestion, is possible to change the name? I mean the original is Olauncher, your can be named OCF or OlauncherCF.
Thanks for your work 🙏

**Comment by lichingyun** [comment]
![IMG-20220502-WA0002](https://user-images.githubusercontent.com/79099214/166319160-4b5f5c0a-529a-4524-a535-540e60c89677.jpg)
picture of the settings 😍

**Comment by lichingyun** [comment]
![Uploading Screenshot_20220502-192853_Olauncher.png…]()

picture of the settings 😍

**Comment by jooooscha** [comment]
I am very happy that it works now.

However, please open a new issue for other features/problems. Otherwise keeping overview will be very hard. :)

**Comment by lichingyun** [comment]
@jooooscha 
after reading the closing of error #20 today I try to install OCF 1.6 from github but I have the same error, I can't install the apk,  now I wait version 1.6 from fdroid
