### ISSUE TITLE
Lock "screen rotation" for Olauncher

### ISSUE THREAD

**Issue by ongots** [jooooscha/Olauncher#100]
Rotating the screen causes layering and interface distortion, and is not usable. Need to block him.

**Comment by jooooscha** [comment]
Could you please decribe in more detail what the problem is? Please provide detailed steps to reproduce, app version, etc

**Comment by ongots** [comment]
https://user-images.githubusercontent.com/43604031/178916537-1de50d68-a620-4fa3-9e5f-f839cf44f145.mp4

The video shows:
-the clock overlaps with the list of apps
-applications don't fit.
-the wallpaper looks bad
-the keyboard completely obscures the app list
-white background above the keyboard
-blank app list after going back to vertical mode

Forgot to make a video:
-If you open the settings and tilt the phone always pops up the launcher selection panel.

olaunchercf 1.0.0
Android 8.0.0
Sharp Aquos C10
Gboard keyboard

**Comment by Ilithy** [comment]
> The app should not be rotatable on a phone 🤔
> 
> I will look into this, why this is enabled on your phone

That's right, on my devices (phone of course) Olauncher CF does not manage the rotation of the home screen

@ongots: Is this a systematically reproducible bug?

**Comment by ongots** [comment]
Olauncher rotates if it is enabled in notification panel.
Other applications work correctly. Always fixed or rotate if enabled.
Nova launcher doesn't rotates.

**Comment by Ilithy** [comment]
> Olauncher rotates if it is enabled in notification panel.  


For accuracy, on my Pixel 6 pro under Android 12L (Grapheneos) this is not the case.

**Comment by jooooscha** [comment]
Googling you device it looks like it's a tablet but with a more phone like aspect ratio?

On tablets rotating is indeed enabled, so I consider at least the crashes to be a bug.

However, if you enable so many apps on you home screen that they don't fit any more, that is on you, isn't it?

**Comment by ongots** [comment]
Sharp Aquos C10 (S2) is a smartphone with 5.5" 1080 x 2040px screen

**Comment by Ilithy** [comment]
Have you rebooted your device recently? ¯\_(ツ)_/¯

**Comment by ongots** [comment]
Did not help : )

**Comment by jooooscha** [comment]
Mh, ok. I will look into the mechanism that determines whether the app is rotatable or not (Its still part of the original code). Maybe there is a bug, and that is why the app on you phone thinks it should be rotatable.

**Comment by ongots** [comment]
In the original Olauncher, the bug is reproduced.
Fixed in Ultra launcher:
https://github.com/tanujnotes/Ultra/commit/0dbd928048cbe310564ff5821e73e0ac9f767d03

**Comment by Ilithy** [comment]
Yes, but in this case, the rotation will be blocked also on the tablets (if I'm not mistaken), it's a shame.
