### ISSUE TITLE
Add bottom app position option

### ISSUE THREAD

**Issue by ongots** [jooooscha/Olauncher#102]
![Screenshot_2022-07-15-13-10-49](https://user-images.githubusercontent.com/43604031/179213711-0fe1cc9d-1090-429d-8fed-0437307fb7a9.jpg)
As in Ultra launcher.
Also there, the clickable area is reduced to the names of applications, which causes fewer false clicks.

**Comment by Ilithy** [comment]
Hi
1. It's a good idea, it could be part of a one handed mode (I think the app drawer should also react identically to be really convenient).

2. I saw that too, and indeed it would reduce accidental clicks (for the application drawer it does the same and prevents a quick exit by clicking elsewhere than in the list), but this behavior is not very problematic.

this is only my personal opinion ;-)
