### ISSUE TITLE
Change app icon

### ISSUE THREAD

**Issue by jooooscha** [jooooscha/Olauncher#107]
Reminder for me to change the app icon created in #71

**Comment by jooooscha** [comment]
If you merge something, please always use squash-merge. Otherwise it is very hard to fix the commits, if something is broken

**Comment by Ilithy** [comment]
@jooooscha Very well, thank you for the instructions, indeed it is a lot more file to check, I apologize.
 I will avoid merging without your revisions, it is much safer, and allows you to better track the additions
