### ISSUE TITLE
Add an option to disable launcher animations

### ISSUE THREAD

**Issue by ferlanero** [jooooscha/Olauncher#11]
In order to have even a more minimalist launcher, please add an option to disable launcher animations in settings page. This option would be great for increase performance in e-ink devices too (like Hisense A5 Pro & A5 Pro CC or any other e-ink device like Pinetable, Dasung, etc.)

**Comment by jooooscha** [comment]
Nice idea. At this point I am not sure how complex this would be, but I will look into it.

**Comment by jooooscha** [comment]
Which animations exactly do you mean? Do you mean the animation when swiping up?

**Comment by ferlanero** [comment]
> 

Exactly, I mean the animations which occur when:
- swipe up on the main screen to access app list
- long press on the main screen to access settings
- in settings you press over "Olauncher Clutter Free" to access list of hidden applications.

**Comment by jooooscha** [comment]
This will probably be easier after merging #30

**Comment by Mathias-Boulay** [comment]
This could be done via an interpolator "jumping" to the end of an animation, although I'm not familiar with jetpack compose

**Comment by jooooscha** [comment]
After considering, I think this is out of scope for this launcher. As far as I know, animations can be disabled in Android system-wide in the developer settings. I think that's a better place for this option.

Closing for now
