### ISSUE TITLE
Place schreenshots in correct dir

### ISSUE THREAD

**Issue by jooooscha** [jooooscha/Olauncher#116]
The images are not shown in fdroid. 
Taking element-android for reference, the images should be in another subdirectory called `phoneScreenshots`

**Comment by Ilithy** [comment]
Hi, done on #117, Just need your approval, thanks

**Comment by Ilithy** [comment]
I merge (little chance of error on this)

**Comment by jooooscha** [comment]
looks good. Thanks :)
