### ISSUE TITLE
Redirected to the wrong settings when pressing 'Set as default launcher' or 'Change default launcher' on EMUI 8.0.0

### ISSUE THREAD

**Issue by CrimsonBloodfang** [jooooscha/Olauncher#123]
#### Short description 
I don't get redirected to the default apps section when pressing 'Set as default launcher' or 'Change default launcher' on EMUI 8.0.0. It went way past it. It should open from Settings>Apps & notifications>Default apps>Launcher.

#### Steps to reproduce 
1. If newly installed, just click 'Set as default launcher'
2. It will redirect to the wrong section (Settings>Apps & notifications>Apps>Settings>Configure Apps)

Or after manually setting it as default launcher
1. Long press Olauncher homescreen.
2. Click on 'Change default launcher'.
3. It will redirect to the wrong section (Settings>Apps & notifications>Apps>Settings>Configure Apps)
#### Environment information 
- Olauncher CF Version: All versions to the current latest V1.0.1
- Install Source: F-Droid
- Device: Huawei P8 Lite 2017
- Android: 8.0.0, EMUI 8.0.0
- Other: Debloated phone

#### Additional elements

Wrong ❌

https://user-images.githubusercontent.com/68450471/182279443-500f3d0e-32da-4685-a511-7a77f4b6fab6.mp4

(Settings>Apps & notifications>Apps>Settings>Configure Apps) ❌

https://user-images.githubusercontent.com/68450471/182280066-562aa66a-e4c6-43f4-8377-58a34d32edf6.mp4

Correct ✔️

https://user-images.githubusercontent.com/68450471/182279586-80342dd6-7e0b-4d7c-963f-002a56178172.mp4

**Comment by jooooscha** [comment]
This is weird, I always get a popup in which I can select Olauncher.

I will look into this as soon as I have time

**Comment by jooooscha** [comment]
This seems to be a bug with EMUI. As far as I can see, there is no easy way to fix this from my side. Also, as this is a pretty minor bug, I will close this for now
