### ISSUE TITLE
Make the empty space beside each apps on the homescreen clickable/pressable

### ISSUE THREAD

**Issue by CrimsonBloodfang** [jooooscha/Olauncher#124]
**Is your feature request related to a problem? Please describe.** 

- It is very inconvenient to accurately press the text/name of an app everytime just to open it. The main dev added 'app alignment' as an alternative solution for this headache but it just doesn't do for me. In my opinion, nothing beats the aesthetic look of the left app alignment, but as a right handed person, yes it'll be difficult sometimes to reach these apps with one hand.

**Describe the solution you'd like** 

- I'd like the convenience present in the app drawer to be applied as well on the homescreen wherein I don't have to tap on the text/name itself but can just tap the empty space beside it. On landscape, these clickable/pressable empty spaces shouldn't overlap with the apps & time/date. 

**Describe alternatives you've considered** 

- I have been renaming my homescreen apps with 'invisible texts or characters' (ㅤ) at the end just to achieve this feature. Normal spaces don't work and lacks the width. Minor problems with this is that it overlaps with time & date on landscape and it sometimes add unwanted spaces underneath/between apps.

**Additional context** 

Just like this

https://user-images.githubusercontent.com/68450471/182285535-d0650259-b1a1-4618-82dc-eb0aa6557b89.mp4

Problem with doing the alternative way on landscape is that some apps overlap with time & date

https://user-images.githubusercontent.com/68450471/182285987-065031a3-7e8d-4088-8235-17ccea3a0153.mp4

Using too much invisible texts or characters on an app with less characters, letters or texts adds unwanted spaces underneath/between apps. Example: Notes

![Screenshot_20220802-113931](https://user-images.githubusercontent.com/68450471/182287272-0c25ff8d-15b2-4b94-86ae-fc7abad645cc.jpg)

I used Version Fork 1.8 in these because I encountered landscape problems on latest v1.0.1 which has been reported on #122

**Comment by jooooscha** [comment]
Thanks for taking your time and describing your problem in such detail. I still have not enough time to work on this project; I will look into this as soon as I have, though

**Comment by jooooscha** [comment]
Now, I am unsure what exactly you problem is. I did not rename my apps like you did, but I can still tap next to the app and it still opens

**Comment by CrimsonBloodfang** [comment]
Oh, disregard this. This feature is already in the latest version 1.0.1, my bad. You were already ahead of me. Been using version fork 1.8 and I was supposed to request it way sooner before the latest versions but I'm late.

**Comment by D-ominik** [comment]
Hi Joscha,

just found your fork and switched from the original version. Thanks for your work!

It would be great if the active area of the home screen apps was an adjustable option. When using Double-Tab-to-Lock, it doesn't work in the apps area because the first tap already launches the app.

In the original, the active area is only as wide as the text is long. I generally found this great because it also reduces accidental launches, but understand that this is of course a matter of personal preference. So configurability would be great.

Bye, Dominik

**Comment by jooooscha** [comment]
Please do not comment other topics to closed isues.
Please open a new one and link the old with "#XX"  where XX is the issue number of the related issue
