### ISSUE TITLE
Option to lock home screen app list.

### ISSUE THREAD

**Issue by Helfexen** [jooooscha/Olauncher#125]
**Is your feature request related to a problem? Please describe.**
I'm installing this launcher on old peoples phones and sometimes they long press on apps on the home screen and change them.

**Describe the solution you'd like**
Just an option to lock long press on home screen applications, app list shouldn't be changed until the option is disabled again from Olauncher's menu.

**Comment by jooooscha** [comment]
This is an easy feature :)
Thank you for your contribution
