### ISSUE TITLE
Rename apps name even on main screen

### ISSUE THREAD

**Issue by ferlanero** [jooooscha/Olauncher#13]
OLauncher Clutter free already has the ability of renaming apps in normal app list (thanks God). But this creates inconsistency with the app list showed on main screen as this still shows original app names. Please extend renaming apps capacity to main screen app list.

**Comment by jooooscha** [comment]
I am glad you like my modifications to the original version.

However, your feature request is already possible in the original version. if you place an app on the main screen and long press it again you can insert the new name you want and a rename button will appear. 

Synchronizing the app alias in the app list and in the normal list is not a goal of this fork, as this would require heavy changes to the original architecture of the app. This would have disadvantages, like not being able to fetch new commits from the original version (if there will be any in the future).

i am closing this issue. If I misunderstood your request feel free to further explain your idea :)

**Comment by ferlanero** [comment]
Sorry but I don't understand your instructions. If I place an app in main screen & then long press this app, Olauncher takes me again to app list to choose the app I want to place in main screen, not showing me any rename button there :/

**Comment by jooooscha** [comment]
Yes, Start typing on the app chooser screen. A rename button will appear.

Changing this behavior would, again, require huge changes in the original app architecture and is, therefore, not a scope of this fork. But I agree this behavior is not optimal.
