### ISSUE TITLE
Extend clock and date arena just as entries

### ISSUE THREAD

**Issue by alekksander** [jooooscha/Olauncher#143]
Would it be possible to have bigger clickable areas for date and clock, just as it works for application entries? In my understanding all available width should evoke clock/calendar.

**Comment by jooooscha** [comment]
I am not sure this would help the user experience. I think it makes it too easy to accidentally click on them. 
For the apps it is a different story, becasue they form clear rows.

I don't know; what do you think?

**Comment by alekksander** [comment]
i'm not a designer in any way, but once i realized apps can be selected this way i intuitively wanted to run date/clock like this too. it was disappointing to see nothing happen. anyhow current clickable area is small and in my opinion too small. even if we forget max width thing, clickable arena should be extended somehow. personally i often use calendar and touching this tiny short date under clock is often challenging.

**Comment by jooooscha** [comment]
Even now, people are complaining that the click-areas overlap #150.
I don't think increasing them further is advisable. I might even think about making the areas for the apps smaller
