### ISSUE TITLE
Double tap to lock won't let me unlock using my phone's fingerprint scanner

### ISSUE THREAD

**Issue by CrimsonBloodfang** [jooooscha/Olauncher#148]
#### Short description 
When I double tap to lock and then I try to unlock my phone through its fingerprint scanner, I'm always prompted to unlock my phone using my lock screen password instead. It also says on the lock screen, 'Device administrator locked device'.

#### Steps to reproduce 
1. Enable 'Double tap to lock'
2. Activate or grant it device administrator
3. Double tap the home screen to lock the phone
4. Now unlock the phone using your fingerprint scanner
5. Phone stays locked and you'll be prompted to unlock using your lock screen password

#### Environment information 
- Olauncher CF Version: 1.1.0
- Install Source: F-Droid
- Device: Huawei P8 Lite 2017
- Android: 8.0.0, EMUI 8.0.0
- Other: Debloated phone

#### Additional elements

>It also says on the lock screen, 'Device administrator locked device'.

![Screenshot_20220814-162744](https://user-images.githubusercontent.com/68450471/184529309-8e5c05dd-c103-4371-847e-d563fd109e4c.jpg)

**Comment by jooooscha** [comment]
Like with #152 #151, this seems to be EMUI related; I cannot confirm this on my device. I guess there is no way around this as it seems to be a "feature" of EMUI. Unless you can show other apps that get around this (if possible open source, so I can look how they do it) I will not be able to fix this. Closing for now
