### ISSUE TITLE
Version info at the bottom of Olauncher CF settings isn't following the theme mode

### ISSUE THREAD

**Issue by CrimsonBloodfang** [jooooscha/Olauncher#149]
#### Short description 
The version info text color is grayed out or not following the theme mode. It looks out of place and barely visible on some wallpapers.

#### Steps to reproduce 
1. Long press home screen
2. Scroll down at the bottom
3. Look at the bottom right

#### Environment information 
- Olauncher CF Version: 1.1.0
- Install Source: F-Droid
- Device: Huawei P8 Lite 2017
- Android: 8.0.0, EMUI 8.0.0
- Other: Debloated phone

#### Additional elements

![Screenshot_20220814-164419](https://user-images.githubusercontent.com/68450471/184529723-205464ca-c264-42fc-8d0b-c59930fc57ca.jpg)

**Comment by jooooscha** [comment]
It is supposed to be barely visible. It is only used to help report bugs. Therefore, I will close this for now
