### ISSUE TITLE
Can't open the centered clock & date on landscape

### ISSUE THREAD

**Issue by CrimsonBloodfang** [jooooscha/Olauncher#150]
#### Short description 
The clickable areas of a centered clock & date is overlapped by the application next to it.

#### Steps to reproduce 
1. Center your clock & date alignment
2. Make sure to have as much as seven apps on either left or right alignment
3. Try to click on clock & date, it will open the app beside it

#### Environment information 
- Olauncher CF Version: 1.1.0
- Install Source: F-Droid
- Device: Huawei P8 Lite 2017
- Android: 8.0.0, EMUI 8.0.0
- Other: Debloated phone

#### Additional elements

https://user-images.githubusercontent.com/68450471/184530237-39588e18-1e1c-4026-b7b1-c502649a60f1.mp4

**Comment by jooooscha** [comment]
This seems to be related to #122. Landscape mode on phones is a bug, not a feature (so far only reported on EMUI). In the future I will try to find a way to disable landscape mode on all phones, even EMUI

**Comment by jooooscha** [comment]
closed with #161
