### ISSUE TITLE
Add option to map hardware buttons to apps

### ISSUE THREAD

**Issue by chezui** [jooooscha/Olauncher#154]
**Is your feature request related to a problem? Please describe.** 

I'm using a candybar android (AGM M7), would be great if I can map the physical buttons to specific apps such as Contacts/Call History etc.

**Describe the solution you'd like** 

Add option to press key to launch an app.

**Describe alternatives you've considered** 

- just use the default Launcher3 that the phone shipped with.

**Additional context** 

- Add any other context or screenshots about the feature request here.

**Comment by alekksander** [comment]
there are foss applications for that like key mapper, i personally don't see how does it belong to this launcher.

**Comment by Ilithy** [comment]
I agree with @alekksander, this is not the purpose of an launcher, moreover the majority of smartphones have very few physical buttons, this is a lot of work for the developer for little benefit to the vast majority of users _(this is just my opinion)_
