### ISSUE TITLE
Disable swipe gestures and clicks on the clock

### ISSUE THREAD

**Issue by ChristophHeilmann** [jooooscha/Olauncher#165]
I can't disable a gesture like in the original app. Can you add this feature?

**Comment by jooooscha** [comment]
I assume you mean the left and right swipe gestures?

**Comment by ChristophHeilmann** [comment]
I mean all swipe and click gestures. Long press on a click or swipe gesture: off.

**Comment by jooooscha** [comment]
I am not sure you can disable the swipe up gestures in the original (which would make no sense anyway), so I assume you only mean the left and right swipe gestures.
Which click "gestures" do you mean?

Could you please describe your problem in detail, and please you the issue template.

**Comment by ChristophHeilmann** [comment]
**Is your feature request related to a problem? Please describe.** 

I installed Olauncher Clutter Free on some ereaders of older people who are not trained to use electronic devices. They are confused when they made an accidentally movement like clicking or swiping on the screen and open an app which they not intended.
This issue belongs to:
Swipe left app
Swipe right app
Clock click app
Date click app

**Describe the solution you'd like** 

It would be nice if you could add an option to disable these functions so people will not confused.

**Describe alternatives you've considered** 

n/a

**Additional context** 

The original app with Swipe left app disabled:





![screenshot_20220828_134822_50](https://user-images.githubusercontent.com/9595209/187479964-1e2627e9-bf41-46d8-b076-f69c7abd9ad5.png)

**Comment by jooooscha** [comment]
Thanks for the clarification. I will look into this.
I really don't like the UX in the original (long click on the text), so I will come up with something else. 
Also I don't have much time currently, so this could take a while
