### ISSUE TITLE
Android TV version

### ISSUE THREAD

**Issue by AntonDzutstsati** [jooooscha/Olauncher#166]
Is there any possibility to adapt Olauncher for Android TV?

**Comment by jooooscha** [comment]
I am not sure the design of this launcher would be particularly good on a TV.
The main interactivity happens through swiping and typing, both of which are not easily possible on a TV.
That being said, I do not own an Android TV, which would make it hard to develop and debug.
I am closing this for now; if you want to, you can still a pull request
