### ISSUE TITLE
Icon support?

### ISSUE THREAD

**Issue by nulledone** [jooooscha/Olauncher#169]
I'm unsure if this really fits the philosophy of this app but would be neat to have an option to show icons. I used to have Niagara and miss its aesthetic.

https://play-lh.googleusercontent.com/JyM7_zwvbM2L7Df8O8-2g4xNQDsELwOTEw0CtcFBnQOHon8UEv9AOIfnV5GZBstfig=w2560-h1440

2 options to enhance user experience.

- Hide names on homescreen, show only icons (tap area for launching app should still be a bit long for ease of access)
- Icon size

**Comment by Npa972** [comment]
Keep it simple please !
There is good app launcher with icons.

**Comment by jooooscha** [comment]
I am on the side of @Npa972 here. This launcher is simple by design and choice. If you want Niagara launcher, you should use that.

**Comment by nulledone** [comment]
> Keep it simple please ! There is good others app launcher with icons. This app is great because of some radicals choices (no icons is one of them)

I get the radical choice but what about having an option to customize the way you want? I think the most important feature of a launcher is to have options rather than locking you off to some pre-defined bullshit. 

Design is simple ok, default options to be that way it is all good, but not even having an option in case you get bored is straight up makes the app obsolescent.

**Comment by Ilithy** [comment]
@nulledone  well nothing prevents you from working on it, instead of complaining about the absence of icons in a launcher specifically without icons, these systematically want everything and are contrary... these that which is absurd I find

**Comment by nulledone** [comment]
> @nulledone well nothing prevents you from working on it, instead of complaining about the absence of icons in a launcher specifically without icons, it's systematically want everything and are contrary... that which is absurd I find

@Ilithy  Since when asking for a feature *that would enhance the end user experience and increase overall userbase of an app* is called complaining? I'd respect the dev's choice if he doesn't want to do at all which is okay it is his app but your attitude and comment is straight up unnecessary.

It is just a FUNCTION, nothing more. Not like you are forced to use it, not like it will change your experience in any way other than just a slider switch at the bottom. For real like if you don't even want to see the slider switch dev can make it a hidden function that opens after doing something like a "up down up down a b a b" stuff. Unbelievable.

**Comment by jooooscha** [comment]
Please have respect for all comments and opinions; and stick to the topic.

**Comment by Ilithy** [comment]
@nulledone I will explain my comment in more detail

>I think the most important feature of a launcher is to have options rather than locking you off to some pre-defined bullshit.

1. Forgive me when you write this, is it respectful according to you? A radical choice is not a bullshit, it's a choice, moreover what's the point of coming to ask again for something illogical given the chosen design?

2. There were already identical request (#40), you probably didn't take the time to check, but I guess for you, to force a developer (alone) who works on his free time (time that is not extensible) for free, is not important.

3. you write that it is enough for the developer to add this or that feature, this or that option, do you realize how much work goes into each request? The coding, the tests etc...
It's not as simple as writing a request.

I am not aggressive, but you are condescending without even respecting the basic rules of courtesy (and respect for the developer), don't you think?
Respectfully
