### ISSUE TITLE
Clock and date - bottom

### ISSUE THREAD

**Issue by ANDREW007CZ** [jooooscha/Olauncher#170]
hi,
I'm opening calendar and clock quite frequently through clock and date. On top it's not easy to reach. I know it would make sense to add shortcuts of them to the list.
But wouldn't an optiom to have clock and date on bottom also make sense in terms of customization? Would love to see that feature :)

Thanks for great work and features you put ontopof this lovely Tanuj's idea. You've made original launcher superb launcher for me. :)

**Comment by jooooscha** [comment]
I am unsure about this. At the one hand, sure, more customization is cool, but on the other hand I don't want to have a complex customization system.

I tend to think that this is a bit out of scope for this launcher.

**Comment by ANDREW007CZ** [comment]
alright, sure, just an idea in case more people would be "bottom oriented", (if you know what I mean). Thans for reply! :)

**Comment by alekksander** [comment]
my first vague idea after reading tihs is to split screen horizontally for config as it is split vertically for now and not to have only left, center and right edge, but also top, center and bottom for more options. i don't have any opinion about that, just thinking out loud.
