### ISSUE TITLE
false alignment of home screen apps in russian

### ISSUE THREAD

**Issue by qube-03** [jooooscha/Olauncher#173]
#### Short description 
when i change my system language, not olaunchers, to russian, the home screen apps are on the right, yet are alignes to be on the left text wise

#### Steps to reproduce 
1. put home screen apps on the right
2. change system language to russian
3. see bug 

#### Environment information 
- Olauncher CF Version: 1.2.4
- Install Source: Droid-ify
- Device: Samsung Galaxy S20 FE
- Android: Stock
- Other: debloated a little with adb, not rooted

#### Additional elements
![image](https://user-images.githubusercontent.com/92535344/188059605-9f1f2e78-c54b-4a64-8fcf-8b8d500deb00.png)

**Comment by jooooscha** [comment]
Thanks for reporting, I will look intoit
