### ISSUE TITLE
Ability to differentiate between same named apps

### ISSUE THREAD

**Issue by nulledone** [jooooscha/Olauncher#174]
**Is your feature request related to a problem? Please describe.** 

No.

**Describe the solution you'd like** 

Perhaps show package name on app list if it is duplicate?

**Describe alternatives you've considered** 

Show difference in package name rather than full name.
Show first letters of the package name if it is different
Show last letters of the package name if it is different.

**Additional context**

**Comment by jooooscha** [comment]
Please use the feature templates.

**Comment by nulledone** [comment]
> Please use the feature templates.

Done.

**Comment by jooooscha** [comment]
Ok, I rephrase my request. 
Please give enough information and motivation for your feature, so that we can understand what you want and why you think the change improves this project.

You want the name of the package? Would that look awful?
Why don't you just rename one of the apps? For example, if you have too apps called "maps" just rename one of them to "google maps" or similar.

**Comment by nulledone** [comment]
Exactly as you've mentioned, too many maps apps. Initial setup was somewhat hard since I need to rename them one by one by going into the app. The easiest solution I have thought of was to show package name under the app name in paranthesis. Or rather like Maps (2), Maps (3).

It is hard to get motivation for your use case since this is highly personal use-case, time to time I also need to reinitialize many things so it is painful to rename them again and again.

**Comment by jooooscha** [comment]
Showing them as Maps (n) does not make sense as they are showed in order, anyway. Therefore, the second maps app would be maps (2) and the third would be maps (3). As you see, the number does not add any information.

Showing the package name would look awful in the list. It would add unnecessary clutter.

We have a merge request for a backup and restore functionality (#69). I think this is a much better solution to your problem.
