### ISSUE TITLE
Non-FOSS in F-Droid build

### ISSUE THREAD

**Issue by licaon-kter** [jooooscha/Olauncher#181]
Ref: https://gitlab.com/fdroid/fdroidserver/-/issues/1004#note_1095002759

Ref:  https://github.com/jooooscha/Olauncher/pull/30

Ref alternative: https://github.com/SceneView/sceneform-android

Ref: https://github.com/streetcomplete/StreetComplete/issues/4289

**Comment by jooooscha** [comment]
Can you jump-start me here? I cannot follow what is happening. Do I need to do something?

**Comment by jooooscha** [comment]
So building with gradle is the problem?

**Comment by licaon-kter** [comment]
We are lost in translation :)

**Comment by jooooscha** [comment]
Could you please elaborate.

You said 'without that library'. I assume you mean the google ar core? Why should that be present in my app?

You said with a 'gradle flavor'. 'Flavor' is often used when you mean a slightly modified version of the original. So my question is, what has gradle to do with the library? Therefore, I askes if using gradle is the problem.

If you don't know the answers, I will find time to find it out myself. (which could take a while). I only figured that if you describe the problem in a few sentences, I could fix the problem faster.

And finally, where are we lost in translation?

**Comment by licaon-kter** [comment]
> You said 'without that library'. I assume you mean the google ar core? Why should that be present in my app?

Because you've added it in https://github.com/jooooscha/Olauncher/pull/30 here: https://github.com/jooooscha/Olauncher/blob/v1.2.5/app/build.gradle#L92

> So my question is, what has gradle to do with the library? Therefore, I askes if using gradle is the problem.

With a gradle flavor you can separate the app in two parts, one with the proprietary library say for Google Play store and one without for F-Droid. eg. flavors: https://github.com/iNPUTmice/Conversations/blob/master/build.gradle#L143-L150 and separation: https://github.com/iNPUTmice/Conversations/blob/master/build.gradle#L78-L79

Gradle has the solution, or the tools.

**Comment by jooooscha** [comment]
Yes, thanks for your help. I understand the situation now. I wasn't aware that I added the ar core, or that it is non-free.
I removed it; its not a runtime dependency anyway.

This is closed in v1.2.6

**Comment by licaon-kter** [comment]
Thanks, builds fine
