### ISSUE TITLE
Alignment of applications is not preserved after changing their number

### ISSUE THREAD

**Issue by Npa972** [jooooscha/Olauncher#185]
#### Steps to reproduce
1. open OLauncher and add an app (5 to 6 in my case)
2. Close menu ; new app appear on main screen but alignment is left (my settings was "center")
3. I have to shut down Olauncher (force to stop) or restart the phone to get back the apps in center alignment (my settings)

#### Environment information 
- Olauncher CF Version: 1.2.6
- Install Source: fdroid apk
- Device: redmi 9c
- Android: 11
- EMUI?: ???
- Other: 

It is not a big deal.
Thanks

**Comment by jooooscha** [comment]
This only happens with extended click area on.

Will fix it for the next version.
