### ISSUE TITLE
Add !bang search

### ISSUE THREAD

**Issue by Voralberg** [jooooscha/Olauncher#186]
**Is your feature request related to a problem? Please describe.**

More than a problem it would be really a time saver. Wouldn't be possibile to add the supports for the [!bang search](https://duckduckgo.com/bang) as was added in the original [Olauncher v3.5.3](https://github.com/tanujnotes/Olauncher/releases/tag/v3.5.3)?

Also I would like to thank you for your work, I use this version of Olauncher on all my devices. It's just a misfortune that it doesn't support the [!bang search](https://duckduckgo.com/bang), as previously mentioned, nor the web app shortcut using Android System WebView (e.g. The one created with [Native Alpha](https://github.com/cylonid/NativeAlphaForAndroid)).

**Comment by jooooscha** [comment]
We plan on adding suuport on web apps.
The bang search, however, is not planned as out of scope. This is a mininal launcher that tries to solve one thing and that thing good.
