### ISSUE TITLE
Apps installed on SD card disappear from homescreen after shutdowns

### ISSUE THREAD

**Issue by XavierBeguin** [jooooscha/Olauncher#194]
#### Short description
Shortcuts to apps installed on my SD card are lost after each shutdown.

#### Steps to reproduce
1. Add a shortcut to the homescreen to an app installed on the SD card
2. Shutdown and restart (or reboot) the phone
3. The shortcut is gone, replaced by "App"
4. Same behaviour with any app installed on the sd card

#### Environment information
- Olauncher CF Version: v1.2.6
- Install Source: F-Droid
- Device: Samsung J7-2016 (SM-J710FN)
- Android: Stock 8.1.0
- EMUI: no
- Other: some apps moved to an internal SD card

#### Additional elements
On startup, apps installed on the SD card are only available to the system 2 or 3 seconds after OlauncherCF starts (they only appear 1 or 2 seconds after startup on some proprietary launchers). OlauncherCF manifestly cannot see them on startup and removes them from the homescreen.
The issue is the same with the original Olauncher app (v3.5.4).
Thanks for your work !

**Comment by jooooscha** [comment]
This probably has to do with the fact that reading apps from the SD card is much slower. During this time, Olauncher does not know there are installed and removes them from the home screen.

I changed some of the app loading logic for another reason in the latest release (1.2.10). It is already recognized by f-droid, but will most likely take another 3 to 4 days until it will be available in the store.
When it is released, could you try if that fixes your bug?
If not, please report here, and I will see if I can help you some other way

**Comment by XavierBeguin** [comment]
Thanks for your quick reply!
Sure, I'll try version 1.2.10 when it'll be available in the store and I'll report the result here.

**Comment by XavierBeguin** [comment]
I've installed the latest release (1.2.10) and I'm happy to report that it resolves the issue!

I can now fully enjoy OlauncherCF :smile:
Thanks for the improvement that also fixes my issue!
