### ISSUE TITLE
Status bar do not follow theme mod

### ISSUE THREAD

**Issue by Npa972** [jooooscha/Olauncher#199]
I think status bar always stay in clear mode on home screen.
It's ok in app drawer.
Theme setting = follow system (dark theme scheduled at night)
Thanks
OL 1.2.10
Android 11
Xiaomi redmi 9C
Thanks

**Comment by jooooscha** [comment]
I am not sure what you mean with clear mode. I don't know your device or your android branding (every brand customizes their android differently).

Could you add some screenshots, steps to reproduce, all relevant settings?
If you use the issue template, there is everything there, I need.

Closing this one, feel free to open a new one with the correct issue template.

**Comment by Npa972** [comment]
Yes you're right i was not very precise...
Anyway this is not a OLauncher bug.
I investigate and in fact it's the Xiaomi OS that changes the status bar according to the screen background (clear or dark).
