### ISSUE TITLE
cannot install OCF 1.6 from github

### ISSUE THREAD

**Issue by lichingyun** [jooooscha/Olauncher#23]
@jooooscha 
after reading the closing of error #20 today I try to install OCF 1.6 from github but I have the same error, I can't install the apk,  now I wait version 1.6 from fdroid

**Comment by jooooscha** [comment]
Did you try the apk from my nextcloud? https://next.serwm.com/s/n7wo4nMn6w3qwm5

**Comment by lichingyun** [comment]
thanks, thos work 🙏

7 mag 2022 22:33:21 jooooscha ***@***.***>:

**Comment by jooooscha** [comment]
Ok, if 1.5 works 1.6 should work, too. Maybe the github apk is faulty. Let's wait for the fdroid release (should be any day now) and see if that works

**Comment by jooooscha** [comment]
Version fork1.6 is now available on fdroid. Did you try to install it, yet?

**Comment by lichingyun** [comment]
yes @jooooscha I have install 1.6 from fdroid, this evening when I come back home I configure it

**Comment by jooooscha** [comment]
Then I consider this issue closed
