### ISSUE TITLE
Add the possibility to choose the default calendar app

### ISSUE THREAD

**Issue by znvcx** [jooooscha/Olauncher#24]
Hello,

I would like to suggest to add the possibility to choose the default calendar app in the settings. So, when we tap the date on the widget, the previously chosen calendar app is launched instead of the default one.

Thanks.

Best regards.

**Comment by jooooscha** [comment]
This is actually one of the first features of this fork. Did you install my forked version?

If you installed the app over the play store, you did install the original version. This fork is not (yet) available on the play store.
Please download Olauncher Clutter Free version from the f-droid store.

**Comment by znvcx** [comment]
I've downloaded it from f-droid and got an update this morning.

I have the option in the settings indeed but even though I did change it, it's still the default app that is launched.

**Comment by jooooscha** [comment]
I cannot confirm. Please check that you have version fork1.6 installed

**Comment by znvcx** [comment]
I have the 1.6fork.

But now it works.

I have restarted my phone and checked the version and it still didn't work. It has worked after I changed the clock app settings for another app and back again to clock. Then both clock and date worked as expected.

For me it's okay. Thank you!

**Comment by jooooscha** [comment]
I am glad I could help
