### ISSUE TITLE
Hidden work profile apps disappeared

### ISSUE THREAD

**Issue by extremelyonline** [jooooscha/Olauncher#292]
### Checklist

- [X] I have searched for existing issues about this bug.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.
- [X] I know that not filling out all information will greatly reduce the devolopers chances of debugging your issue

### Bug description

When I hide some work profile apps, they disappeared from OlauncherCF completely. I've renamed the app to a non-english name prior to doing so.

### Steps to reproduce the bug

/

### OlauncherCF Version

latest

### Android Version

Stock Android 6

**Comment by jooooscha** [comment]
Please provide steps to reproduce.

The following steps do not reproduce the bug on my device:

1. Install and configure Shelter
2. Copy app
3. Hide work version of app

The work version can be found in the hidden menu as expected

**Comment by jooooscha** [comment]
Did you check if the app is shown under its original name?

**Comment by jooooscha** [comment]
No problem. I am glad, its now working for you :)
