### ISSUE TITLE
new features from mLauncher?

### ISSUE THREAD

**Issue by lichingyun** [jooooscha/Olauncher#312]
### Checklist

- [X] I have searched for existing issues about this feature.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Motivation

the development of mLauncher is finished, because the developer want to concentrate only in his project Easylauncher.
Can the repo and the features of mLauncher be used in Olauncher CF?

### Feature description

this is my idea 🙏

**Comment by harmtemolder** [comment]
FYI: https://github.com/DroidWorksStudio/mLauncher

**Comment by jooooscha** [comment]
> Can the repo and the features of mLauncher be used in Olauncher CF?

I am not sure what you mean by this.

I currently do not actively work on this code base. If you want to create a PR with changes, I could find the time to look at your changes and consider merging them.

**Comment by lichingyun** [comment]
Hi Jooooscha, I don't know how to create a PM 🙏
