### ISSUE TITLE
Update F-Droid Build

### ISSUE THREAD

**Issue by rtfmkiesel** [jooooscha/Olauncher#313]
### Checklist

- [X] I have searched for existing issues about this feature.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Motivation

The current F-Droid build is outdated.

### Feature description

The current version is 1.6.5. I don't know what triggers F-Droid to create a newer build, but could you please investigate this?

**Comment by jooooscha** [comment]
I currently do not have the time to investigate this. You can, however, download the newest version of this launcher from the GitHub release page.

https://github.com/OlauncherCF/OlauncherCF/releases/tag/v1.6.9

**Comment by rtfmkiesel** [comment]
This sadly requires a re-installation as the signing keys do not match.

For the next time, just leave the issue open, as it is, in fact, an open issue.
