### ISSUE TITLE
"Hide status bar" option sometimes leaves status bar visible

### ISSUE THREAD

**Issue by crankc** [jooooscha/Olauncher#34]
1. Disable "show status bar." It disappears from the home screen, as intended.
2. Swipe down from the **_middle_** of the screen. Status bar shows up, and disappears again when swiping back up, as intended.
3. Now swipe down from the very **_top_** of the screen, starting from beyond the screen edge. Status bar shows up and now stays up even after swiping the quick menu away.

Reproducible on all my devices, if this is also something only on my end, i'll consider my devices possessed. :)

**Comment by jooooscha** [comment]
I can confirm this behavior, but I guess this is android related and not the fault of the app. 
Also, this is such a minor thing that I don't think it is worth investigating.
PRs welcome if you find anything, but I will close this for now
