### ISSUE TITLE
Thanks! 😍

### ISSUE THREAD

**Issue by lichingyun** [jooooscha/Olauncher#35]
![Screenshot_20220518-172955_Olauncher](https://user-images.githubusercontent.com/79099214/169085033-ac9ea073-ab8b-4155-9ddd-4536d77e5e05.png)
Today the update from Fdroid bring me OCF 1.7!
the "double tap to sleep" is working 👍
now this launcher is nearly perfect 😍
I am very happy to be part of this group as a translator and not only as user 🎉

**Comment by jooooscha** [comment]
I thank you for this lovely comment ❤️
