### ISSUE TITLE
Setting a left/right swipe app from work profile results in "App not found"

### ISSUE THREAD

**Issue by perzarys** [jooooscha/Olauncher#37]
When you set an app which is in your work profile as your "Swipe left/right app" in Settings > Gestures, it won't open on swipe. 
Instead, a toast notification appears at the bottom, containing the following text: "App not found". 
If you try to open said app from the App list, it works fine.
I've opened this issue in the original Olauncher repo as well, but no response as there currently seems to be no active development, sadly.

**Comment by jooooscha** [comment]
I assume @Ilithy is correct and this is not an OlauncherCF bug.

If this assumption is false, please let me know
