### ISSUE TITLE
Number of apps on the screen

### ISSUE THREAD

**Issue by lichingyun** [jooooscha/Olauncher#43]
Hi all!
I use OCF with normal or small text size, based on the wallpaper I use.
Is possible to have 9 or 10 app to show on the homescreen?
Now the maximum is 8.
There is a tread in the github pages of the original Olauncher.
What do you think?

**Comment by jooooscha** [comment]
Sure, as soon as I have time :)

**Comment by jooooscha** [comment]
Added in #47.

I have simplified the architecture so that the number of apps can now be set by one single variable. I have set it to 15 for now. I will merge this later, it will be part of the next release.
