### ISSUE TITLE
Possible to add option to display only the date?

### ISSUE THREAD

**Issue by Blake-LeBlanc** [jooooscha/Olauncher#45]
Since the status bar already displays the time, would it be possible to give the user the option to only show the date on the home screen?

Thank you!

**Comment by jooooscha** [comment]
We would need to test how this would look. I could test this on a separate branch, as soon as I have time

**Comment by Blake-LeBlanc** [comment]
Okay! Absolutely no rush, thanks for considering @jooooscha !

**Comment by Blake-LeBlanc** [comment]
Thank you so much @jooooscha , it looks great!
