### ISSUE TITLE
Fonts customization

### ISSUE THREAD

**Issue by Ilithy** [jooooscha/Olauncher#49]
Hi; 
First of all, thank you so much for the work done on Olauncher CF,
I love it, it's close to perfection, and it's thanks to you @jooooscha  <3.

Would it be possible to add font customization options to Olauncher CF UI?

_In my opinion, this is one of the elements that it would be nice to be able to personalize._

* By adding several selectable fonts

* As an additional option, it would be huge to be able to add these own font files (TTF,
OTF, WOFF/WOFF2, EOT, SVG)

* Be able to change the font colors

_**This request is in addition to the customization of the font size (discussed on #42)**_
Thanks.

**Comment by jooooscha** [comment]
This could be more involved than you might think. I will see what I can do

**Comment by Ilithy** [comment]
I imagine, this represents a lot of things to add,
but it is absolutely not urgent,
take the time,

thank you for your attention

**Comment by jooooscha** [comment]
As far as I can tell, you have to include all selectable fonts in the app at compile time.
After considering, I think this is out of scope for this launcher, this is more a thing for the operating system.

Closing for now
