### ISSUE TITLE
[Feature Request] Option to display upcoming alarm next to or above clock

### ISSUE THREAD

**Issue by urmomsangus** [jooooscha/Olauncher#55]
Launchers such as KISS will display the upcoming alarm by the clock, which is a useful feature so you can ensure your alarm is set properly without clicking on the clock.

The title states "above" but the placement would probably be better below the clock.

Thanks.

**Comment by jooooscha** [comment]
My goal for this fork is to keep the launcher simple and focused. Therefore, I am not sure if anything not launcher-specific fits into this. With this issue, I am open for discussion, but at this point I am leaning more towards not implementing this.

**Comment by urmomsangus** [comment]
I was thinking, this is probably best left up to the widget function which is how KISS does it (I'm assuming not all default clock app widgets even provide this).

I'm doubting this launcher will do widgets ever, but I don't know. I think it was on the upstream roadmap, but that doesn't mean you have to follow upstream anyway.

So, I'm going to close this unless for some reason you want it left open.

Thanks again.
