### ISSUE TITLE
App drawer text alignment

### ISSUE THREAD

**Issue by TettaVolante** [jooooscha/Olauncher#57]
It would be nice to be able to align the text in the app drawer to the center and right too.
It can be done either with:

- separate option in the menu
- automatically aligns with the home screen app list

I have no notions of android programming but I guess the latter would be easier to implement to the detriment of customization.

**Comment by jooooscha** [comment]
At least the latter should be easy to do. I will look into this

**Comment by jooooscha** [comment]
I just looked into this. This feature is actually already there. If you set your alignment to right, and then long click on the `right` text again, the orientation will be applied to the app list, as well.

Makes my job easier :) Only need to make this discoverable, now

**Comment by TettaVolante** [comment]
I didn't think about trying that at all. The same problem applies to the 'sync theme with device' option that is hidden behind a long press. I don't understand this design choice at all. Thank you for looking into it.

**Comment by jooooscha** [comment]
I want to improve the discoverability of this feature before we can close this

**Comment by TettaVolante** [comment]
Ok, sorry I'm still new to this .

**Comment by jooooscha** [comment]
Don't worry :)

**Comment by jooooscha** [comment]
Will be fixed in #30
