### ISSUE TITLE
Renaming duplicated

### ISSUE THREAD

**Issue by legion1978** [jooooscha/Olauncher#63]
Hi there. if there are 2 apps with the same name, renaming one causes the other one to be renamed as well.

-open drawer
-rename  one app
-close/reopen drawer, both apps will have the new name
:)

**Comment by jooooscha** [comment]
Thanks for reporting. With which two did you observe this behavior?

**Comment by legion1978** [comment]
Hi. 
it actually gets weirder. i cannot rename it back to the original name. the "rename" Button changes to "cancel" and cant save it.
tried with (photo) gallery and calendar, which i have double apps.
system language is spanish, in Olauncher tried system, spanish and english setting.

**Comment by jooooscha** [comment]
Could you share a link to the two apps you are having this problem with? I need this to try to reproduce the problem

**Comment by darcybgoode** [comment]
Hello.
This bug affects me too. To reproduce it you can install for example "Google Maps" and "Yandex Maps" they both will be called "Maps" in the launcher. Then try to rename any of those and you will still have two apps with the same new name.

**Comment by jooooscha** [comment]
Thanks, I will look into it :)
