### ISSUE TITLE
[Info] help for translators

### ISSUE THREAD

**Issue by Ilithy** [jooooscha/Olauncher#70]
Here is a quick guide for translators who want to help Olauncher CF, here are the possible methods:

- Forked the repository
![Screenshot_20220703-115618](https://user-images.githubusercontent.com/36798218/177034579-c26b46f4-79ae-486f-9283-7065e688f7f8.jpg)

- Copy the `strings.xml` file located in `Olauncher/app/src/main/res/values`
![Screenshot_20220703-115208](https://user-images.githubusercontent.com/36798218/177035171-664ba720-fe5d-4e5d-9b3d-af7c2ab8a785.jpg)

- Create a folder `values-[your-language-code]` (_like_ `values-es` for Spanish language)
in `Olauncher/app/src/main/res/` for the translated strings.xml file.
![Screenshot_20220703-120840__01](https://user-images.githubusercontent.com/36798218/177035327-1b066f77-7047-4f98-926e-0881e0c6632b.jpg)

>tip: to create a file subdirectory, simply add a slash (/) after the folder name to enter the folder and be able to create the files there
>Tip 2: [here is a list of country codes](https://countrycode.org/) 

- once your translated `strings.xml` file has been created and filled in, click on the "create new file button"

- Perform the same operation for the files:
 . full-description.txt 
 . short-description.txt
located in `Olauncher/fastlane/metadata/android/en-US`
![Screenshot_20220703-122700](https://user-images.githubusercontent.com/36798218/177035591-08eaa927-d685-43d5-a8bd-282035ada107.jpg)

- Create a folder named like `en-US` **but using your country code**  in `Olauncher/fastlane/metadata/android/` for translated description files, like for the strings.xml file...it's almost done ;-)

these three files (translated) create in the correct folders, you can perform a PR: 
![Screenshot_20220703-123644__01](https://user-images.githubusercontent.com/36798218/177035871-eefbea8d-a40f-47a3-8dd3-440c06bef670.jpg)

And There you go! all you have to do is wait for the developer to merge your additions...

- **Or simply make the translation of the files mentioned, then share on this issue the files translated by you**

Many thanks <3

**Comment by Ilithy** [comment]
@jooooscha My apologies, I created this to help the translators I invite to translate your application, if it bothers, delete it (close the issue)

**Comment by jooooscha** [comment]
This is very great!

My only concern is if is will be found here as an issue. May be we should create an wiki entry and link to it in the readme. What do you think?

**Comment by Ilithy** [comment]
indeed, it's an excellent idea, a link in the Readme (in the contribution section) to start will guide more effectively towards this guide.
    For the wiki, maybe you want something more specific?

**Comment by jooooscha** [comment]
What do you mean with `something more specific`?

I have created a wiki entry and gave you access to the repo. If you want you could copy your tutorial there. 
Having the wiki entry makes it also easier for other people to change and update you tutorial if anything changes in the future

**Comment by Ilithy** [comment]
I wanted to imply a more complete, explicit and clear tutorial, I wonder if it could not be (significantly more)

I've added this (slightly modified) to the wiki, feel free to modify (or delete) it at your convenience; and thanks for preparing the work for me, it helped.

**Comment by jooooscha** [comment]
Thank you so much. This is really great
