### ISSUE TITLE
Replace/Add Screenshots

### ISSUE THREAD

**Issue by jooooscha** [jooooscha/Olauncher#71]
I would like to replace the screenshots in the readme and add some screenshots to f-droid.

As I am sure some of you are much more talented than I am in creating something beautiful, I kindly ask you: If you have any good looking screenshots, please post them here or create a pull request (for the readme).

Thank you very much in advance :)

**Comment by Ilithy** [comment]
Hi @Jooosha, please check out the Readme on your Readme-rework branch, I hope you like it at least partially

**Comment by Ilithy** [comment]
Can we also suggest here a new icon for Olauncher CF?
I know that for a launcher without an icon it seems useless, but it's more to differentiate the two apps, and to look nice on the Fdroid page :-)

What do you think of a basic icon like this one?

<img src="https://user-images.githubusercontent.com/36798218/177209109-26083872-1c0d-42bd-a4e8-3956c0d8d5e7.png" width="50">

**Comment by jooooscha** [comment]
I really like the app icon :) I will to change it with the next release

**Comment by Ilithy** [comment]
Thank you it's very nice, for the icon, I don't know what is needed, so tonight I will provide you with the complete file (in different quality etc), currently I don't have access to it, sorry

**Comment by Ilithy** [comment]
Here are two proposals for header image in relation to your suggestions on #78:
_The images have been compressed, I will upload a full quality image when the final choice is made._

![Samsung Galaxy S20 Ultra Presentation-min](https://user-images.githubusercontent.com/36798218/177330121-f48d1422-8a72-4e60-a85c-b4d4137c929b.png)

![Samsung Galaxy S20 Ultra Presentation(1)-min](https://user-images.githubusercontent.com/36798218/177330736-3dbd3242-1278-460e-ae07-daf7dfbb1e78.png)


I can modify this to your liking, change or/and add other captures (I limited myself to four not to do too much), background, layout etc...

**Comment by jooooscha** [comment]
I really like both of them. But if I had to chose, I'd go with the first one

**Comment by Ilithy** [comment]
Ok, so I'm placing this one instead of the previous one, feel free to comment, I don't take this as criticism :-D

**Comment by Ilithy** [comment]
[here is a zip](https://drive.proton.me/urls/89Q530WX0M#ik8amcFnZGto) containing the icon in these different resolutions (with background and foreground assembled, and separate), sorry I'm doing this sharing from a smartphone, so I had to go through my proton drive to do it.

**Comment by jooooscha** [comment]
closed by #78
