### ISSUE TITLE
Apps from work profile on homescreen

### ISSUE THREAD

**Issue by R7010A** [jooooscha/Olauncher#82]
It is not possible to add an apk from my work profile to the homescreen. I installed Microsoft Teams on both profiles (private and work), only the one from the private one can be put on the homescreen.
It does work with original olauncher (tested).

**Comment by Grkrz** [comment]
Yes ,the same issue.

**Comment by jooooscha** [comment]
Thank you for reporting. We had issues with the work profile before. As i do not use a work profile it's hard for me to debug this.

I will look into this eventually, but I cannot guarantee when this will happen

**Comment by Grkrz** [comment]
I can only add that the version before 1.0.0 did not had this issues. After the update things have got bad. Thank you for the replay😉

**Comment by jooooscha** [comment]
I cannot confirm this bug on my device.

What exactly is not working? Why can you not add them to you homescreen, does the app crash?

**Comment by Grkrz** [comment]
They are not shown any more once you delete them. I can remember now.

**Comment by jooooscha** [comment]
I am not sure what you mean, could you give me steps to reproduce this?

**Comment by Grkrz** [comment]
Quickly I can say that if you hide the app which is in a work profile you are not able to make I visible again unless you remove and install the olanucher once again. This is when you have shelter app which creates work prolofile. I don't know if this is still an issue I bessicaly set up everything and have not changed back than.

**Comment by jooooscha** [comment]
So this is a problem with hiding apps.

Is there a problem with apps on the homescreen?

**Comment by R7010A** [comment]
Sorry if I interfere.
I can confirm a problem with apps on the homescreen from work profile. It isn´t possible to link it. The "original" one from the main profile is linked on the homescreen, although I select the one from the work profile.

**Comment by Grkrz** [comment]
OH yes forgot about the main issue! It is not possible to attach the apps from the work profile to the main screen. I have stop using this app that's why I simply forgot about this.

**Comment by jooooscha** [comment]
> The "original" one from the main profile is linked on the homescreen, although I select the one from the work profile.

I can confirm this behavior.
I will look into how to fix this

**Comment by meisme-dev** [comment]
I still have this problem
