### ISSUE TITLE
Lagging on pixel 6 graphenos

### ISSUE THREAD

**Issue by Grkrz** [jooooscha/Olauncher#86]
The app is working slow. When I am tapping on an app sometimes have to type twice for it to work.
It also not closing smoth when I try close the apps.

**Comment by Grkrz** [comment]
That's strange, perhaps beta version has fixed the issue. I am attaching the video which can perhaps present the issue. Unfortunately I cannot record the issue with tapping twice on the app because it is not visible in the video.

Uploading screen-20220707-173609.mp4…

**Comment by Grkrz** [comment]
Apparently I don't know how to attach the video..

**Comment by Ilithy** [comment]
> Apparently I don't know how to attach the video..

you have to wait until the end of the file sending before validating the comment

**Comment by Grkrz** [comment]
https://user-images.githubusercontent.com/107203983/177818224-a3c956d4-587f-4c65-ac6d-9fef1af635e9.mp4

**Comment by jooooscha** [comment]
Did you try to reinstall the app?
How is the performance on you phone with the original version?

**Comment by Ilithy** [comment]
I'm probably saying a stupidity, but it could not be due to the refresh rate of the pixel 6 screen (90Hz) the pixel 6 pro is in adaptive mode on the refresh rate, this may be affecting the smoothness of the animations ?
Because I really don't have the probelems that I see on your video.
(I did not manage to send mine, too bulky)

**Comment by Grkrz** [comment]
Hnm that is strange that the issue exist only on my phone.(pixel 6). Honestly I don't think so the problem is related to the refreshment at all because before I have used huawei p20pro, and everything worked just fine -60Hz. Perhaps when android  13 rolls out will resolve the issue. Thank you for the involvement anyways😉

**Comment by Grkrz** [comment]
> Did you try to reinstall the app? How is the performance on you phone with the original version?

I have reinstalled many times. 
Original version you mean not forked version? Yes I did reinstalled many times ass well. The app response in the same manere. If you mean graphenos launcher, works very responsively and smooth. I would say extremely smooth, no lags etc.

**Comment by jooooscha** [comment]
Do I understanf you correctly, that the original version (by @tanujnotes) is also very laggy for you?

If that is the case debugging this could be a bit more time consuming. You might have luck openening an issue on @tanujnotes repo.

**Comment by Grkrz** [comment]
Yes @tanujnotes also is not working for me. I have tried all the possibilities that's why I decided to make post to you and @tanujnotes. That's OK if you cannot fix it I just gave a try. I think the issue is related to android 12 because the launchers does not receive so much deep access to the system in general. I am dropping the topic here. Thank you for your replay and the time.

**Comment by Ilithy** [comment]
Hello @Grkrz can you confirm that you are still victims of these lag problems?

- Have you installed the latest version? (which is perfectly stable and runs smoothly on my P6P)

Thank you in advance.

**Comment by Grkrz** [comment]
Hello @Ilithy yes i do CONFORM, nothing has changed. Fully updated to the last version. 
I am attaching the article where they mention why there might be an issue.
"Make third-party launchers smooth again"

https://www.androidpolice.com/android-14/

**Comment by githupper** [comment]
Just to highlight I'm using GOS on P6Pro and do not have any performance issue on this launcher.

**Comment by Ilithy** [comment]
Thank you @githupper for this very useful feedback

**Comment by jooooscha** [comment]
I will close this for now. Seems not to be a bug in of this fork
