### ISSUE TITLE
releasing an APK file

### ISSUE THREAD

**Issue by hoasis2** [jooooscha/Olauncher#9]
> Current link to Fdroid is still to the original version. It will be updated as soon as the submission to Fdroid was successful

Do you want to release an APK here until then?

**Comment by jooooscha** [comment]
The first successful build has been done earlier today, so this fork is now available on fdroid.

I have nothing against publishing an apk with every release, but I am not sure how best to approach this. Do you known if there is a github action that we could use?

**Comment by jooooscha** [comment]
Fixed in f297911af804bb92bfa4ca2b51acb2d1f87afe33
