### ISSUE TITLE
Crowdin integration

### ISSUE THREAD

**Issue by Ilithy** [jooooscha/Olauncher#94]
Hi
It could be extremely convenient to use the Crowdin translation platform for this work.
_(given the number of languages that cumulate OLauncher CF)_

- This will greatly simplify the work of contributors, who would not be forced to manipulate PRs, or create issues for adding translations, or updating them. _(or at least offers a new way to do it)_
- minimize the risk of error (such as forgetting backslashes, accidentally deleting necessary elements, etc.)
- In general, this will simplify the management of the various successive updates of the languages.

_I'm thinking of Crowdin's free plan for FOSS projects_

Voici des liens, pour plus d'information:

[Crowdin app on the Github marketplace](https://github.com/marketplace/crowdin/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW40MjM=#pricing-and-setup=)

[Github integration](https://support.crowdin.com/github-integration/)

What do you think?

**Comment by jooooscha** [comment]
I have just looked into it. To integrate crowdin with github, they request permissions to ALL repository, public and private. So that's not gonna happen.

However, we could indeed use is to have better overview and collaboration options :)

**Comment by jooooscha** [comment]
Ok, I tested a bit around. I am not totally happy, but for now we can certainly use it. I will add it to the readme.

**Comment by Ilithy** [comment]
>To integrate crowdin with github, they request permissions to ALL repository, public and private. So 

Yes indeed, I didn't laugh about that.

An alternative way would be to use my Olauncher CF fork as a repo for translations, crowdin would be configured on this one, which copies yours,

**Comment by Ilithy** [comment]
this would be an alternative repo for translation management, without "risk of theft" of your personal repo (I don't care)
